Add patch debugging

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -80,9 +80,11 @@ runs:
       env:
         DIRS: ${{ inputs.policy_dirs }}
         DEST: 'github/${{ inputs.target_dir }}'
-      run: |        
+      run: |
+        set -x
         echo "$DIRS" | tr ',' '\n' | while read dir; do
-          diff -ruN "base/$dir" "update/$dir"
+          echo "diffing base/$dir and update/$dir"
+          diff -ruN "base/$dir" "update/$dir" || echo "Failed to diff" 1>2
         done > /tmp/catalog.patch
 
         echo "Patching with:"
